# # The command below will initialize the Firedancer validator and ran by root
# # firedancer/build/native/gcc/bin/fdctl init all --config config.toml

# # The user below will be used to run the Firedancer validator
# user = "sol"

# # /home/sol/.firedancer/firedancer
# scratch_directory = "/home/{user}/.firedancer/{name}"
# dynamic_port_range = "8900-9000"

# [log]
#     path = "/var/log/solana/solana-validator.log"

# [ledger]
#     path = "/mnt/ledger"
#     accounts_path = "/mnt/accounts"
#     limit_size = 200_000_000

# [gossip]
#     entrypoints = [
#         "entrypoint.testnet.solana.com:8001",
#         "entrypoint2.testnet.solana.com:8001",
#         "entrypoint3.testnet.solana.com:8001",
#     ]


# [rpc]
#     port = 8899
#     private = true
#     bind_address = "0.0.0.0"
#     only_known = true


# [snapshots]
#     enabled = true
#     path = "/mnt/snapshots"

# [consensus]
#     identity_path = "/home/sol/validator-keypair.json"
#     vote_account_path = "/home/sol/vote-account-keypair.json"
#     authorized_voter_paths = [
#         "/home/sol/validator-keypair.json",
#     ]
#     expected_genesis_hash = "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY"
#     known_validators = [
#         "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
#         "dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
#         "Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
#         "eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
#         "9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
#     ]

# # AMD EPYC 7402P (24C/48T)
# [layout]
#     affinity = "0-35"
#     agave_affinity = "36-43"
#     agave_unified_scheduler_handler_threads = 0
#     net_tile_count = 1
#     quic_tile_count = 1
#     resolv_tile_count = 1
#     verify_tile_count = 5
#     bank_tile_count = 15
#     shred_tile_count = 2

#     [tiles.pack]
#         schedule_strategy = "revenue"

# # # AMD Ryzen 9 9950X (16C/32T)
# # [layout]
# #     affinity = "0-25"
# #     agave_affinity = "26-29"
# #     agave_unified_scheduler_handler_threads = 0
# #     net_tile_count = 1
# #     quic_tile_count = 1
# #     resolv_tile_count = 1
# #     verify_tile_count = 3
# #     bank_tile_count = 9
# #     shred_tile_count = 1

# #     [tiles.pack]
# #         schedule_strategy = "revenue"



# The command below will initialize the Firedancer validator and ran by root
# firedancer/build/native/gcc/bin/fdctl init all --config config.toml

# The user below will be used to run the Firedancer validator
user = "sol"

# /home/sol/.firedancer/firedancer
scratch_directory = "/home/{user}/.firedancer/{name}"
dynamic_port_range = "8900-9000"

[log]
    path = "/var/log/solana/solana-validator.log"

[ledger]
    path = "/mnt/ledger"
    accounts_path = "/mnt/accounts"
    limit_size = 200_000_000

[gossip]
    entrypoints = [
        "entrypoint.testnet.solana.com:8001",
        "entrypoint2.testnet.solana.com:8001",
        "entrypoint3.testnet.solana.com:8001",
    ]


[rpc]
    port = 8899
    private = true
    bind_address = "0.0.0.0"
    only_known = true


[snapshots]
    enabled = true
    path = "/mnt/snapshots"

[consensus]
    identity_path = "/home/sol/peng-keys/validator-keypair.json"
    vote_account_path = "/home/sol/peng-keys/vote-account-keypair.json"
    authorized_voter_paths = [
        "/home/sol/peng-keys/validator-keypair.json",
    ]
    expected_genesis_hash = "4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY"
    known_validators = [
        "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
        "dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
        "Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
        "eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
        "9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
    ]

# AMD EPYC 7402P (24C/48T)
[layout]
    affinity = "0-35"
    agave_affinity = "36-43"
    agave_unified_scheduler_handler_threads = 0
    net_tile_count = 1
    quic_tile_count = 1
    resolv_tile_count = 1
    verify_tile_count = 5
    bank_tile_count = 15
    shred_tile_count = 2

    [tiles.pack]
        schedule_strategy = "revenue"

# # AMD Ryzen 9 9950X (16C/32T)
# [layout]
#     affinity = "0-25"
#     agave_affinity = "26-29"
#     agave_unified_scheduler_handler_threads = 0
#     net_tile_count = 1
#     quic_tile_count = 1
#     resolv_tile_count = 1
#     verify_tile_count = 3
#     bank_tile_count = 9
#     shred_tile_count = 1

#     [tiles.pack]
#         schedule_strategy = "revenue"